---
title: "Aitolo"
author: "Nathalie Scott"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Aitolo Binning 


FastQC will be used to spot issues within high throughput sequencing datasets 

```nohup time fastqc -t 15 *.fastq```

FastP is used on the output data from FastQC to provide all-in-one processing and quality control. Output will be given as a FASTQ file. The code below was written in parallel and FastP was ran on four sequences total.

'''fastp --thread 16 -i $SAMPLE_R1_C14 -I $SAMPLE_R2_C14 -o $OUT_R1_C14 -O $OUT_R2_C14 -g -x --adapter_sequence=AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --qualified_quality_phred 33 --overrepresentation_analysis 5 --cut_right cut_right_window_size=5 cut_right_mean_quality=15 --length_required 50 &

fastp --thread 16 -i $SAMPLE_R1_C15 -I $SAMPLE_R2_C15 -o $OUT_R1_C15 -O $OUT_R2_C15 -g -x --adapter_sequence=AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --qualified_quality_phred 33 --overrepresentation_analysis 5 --cut_right cut_right_window_size=5 cut_right_mean_quality=15 --length_required 50 &

fastp --thread 16 -i $SAMPLE_R1_C16 -I $SAMPLE_R2_C16 -o $OUT_R1_C16 -O $OUT_R2_C16 -g -x --adapter_sequence=AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --qualified_quality_phred 33 --overrepresentation_analysis 5 --cut_right cut_right_window_size=5 cut_right_mean_quality=15 --length_required 50 &

echo "Fastp Done"'''

Run FastQC again to determine the quality of the FastP output

```nohup time fastqc -t 15 *.fastq```

After the FastQC output yields the expected parameters, interleave the two files; R1 & R2

'''


